from pydantic import BaseModel
from typing import Optional, Dict, Any

class ComputeTask(BaseModel):
    """
    Definition of a computational task to be executed by miners.
    In early stages, tasks might be pre-defined or generated by the protocol.
    """
    task_id: str
    input_data: str       # Reference to input data (e.g., IPFS CID, Hash, or raw small data)
    algorithm: str        # Identifier of the algo (e.g. "matrix_mult_v1", "llm_inference_v1")
    difficulty: int       # Difficulty parameter (if applicable)
    reward: int           # Base reward for completion (in CPC units)
    expires_at_height: int # Block height after which result is invalid

class ComputeResult(BaseModel):
    """
    Submission of a completed task (Proof of Compute).
    Included in TxType.SUBMIT_RESULT transactions.
    """
    task_id: str
    worker_address: str
    result_hash: str      # Hash of the computation output (deterministic)
    proof: str            # Hex string of proof (could be minimal or large)
    nonce: int = 0        # Nonce for mining-like tasks
    signature: str        # Worker's signature covering (task_id + result_hash + proof)

    def get_signable_bytes(self) -> bytes:
        """Returns bytes that should be signed by worker."""
        payload = self.task_id + self.worker_address + self.result_hash + self.proof + str(self.nonce)
        return payload.encode("utf-8")
